services:
  db:
    image: postgres:latest
    container_name: fim-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    container_name: fim-backend
    ports:
      - "3001:3001"
    user: "root" # Run as root to access root-owned Foundry data directory
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - FIM_FOUNDRY_DATA_ROOT=${FIM_FOUNDRY_DATA_ROOT:-/var/lib/foundryvtt/data}
      - FRONTEND_URL=${FRONTEND_URL} # Add this line
    volumes:
      - ${FIM_FOUNDRY_DATA_ROOT:-/var/lib/foundryvtt/data}:/app/foundry-data-root
    depends_on:
      - db
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data: